### ISSUE TITLE
Definition of scope

### ISSUE THREAD

**Issue by saschafoerster** [n8n-community-node/n8n-nodes-mastodon#6]
I try to create a search-node. Installation was successful. I am able to connect successfully to a Mastodon account. But the scope of the connection falls back to write after reloading, but I want to search, so I now write, read and maybe follow. Is anyone else having the same issue? Or does the scope need to formatted in a certain way?

**Comment by jakevis** [comment]
@saschafoerster let me see if I can repro... I have only used with write - but it should work with read

https://docs.joinmastodon.org/methods/oauth/

formatting should just be "read"
![image](https://user-images.githubusercontent.com/10895705/220435398-f9597cd6-0eff-4a54-813b-755e84ec7ea8.png)

**Comment by saschafoerster** [comment]
Okay, I got it to work! Thank you, maybe read was not activated, while write was.
