### ISSUE TITLE
Remove link to n8n instance from posts

### ISSUE THREAD

**Issue by bartv42** [n8n-community-node/n8n-nodes-mastodon#7]
Hey, I noticed that the posts all contain a link back to my n8n instance. I'd like to not advertise this address too much - is there a way to disable this?

![image](https://user-images.githubusercontent.com/6816469/219657243-93cd9e3a-8f8c-4657-91fb-290111aa70cf.png)

**Comment by jakevis** [comment]
@bartv42 I dont think this is possible. This is posting to your instance as a user on your instance. If that is then federated elsewhere - the data is still pulled from your instance. But maybe I misunderstood?

**Comment by bartv42** [comment]
That's not what's happening here; that link is to the automation tool I'm using to create the post - it doesn't link to the Mastodon instance. It's similar to listing the app one might use to access Mastodon, but in this case it's revealing information that I prefer to keep private. Happy to provide more information via email if that helps.

**Comment by bartv42** [comment]
Any news? :)

**Comment by rmdes** [comment]
Hi @bartv42 this has nothing to do with this N8N node, this is purely a Mastodon feature that you can disable at will : 
![image](https://user-images.githubusercontent.com/12155003/223830980-11436be0-6bf8-433e-8a3b-f444ebdc77a9.png)

**Comment by bartv42** [comment]
Ah I had no idea, thanks!
